version: '3.9'

services:
  backend:
    build: ./websocket  
    image: deno-backend-image
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=my-redis
    networks:
      - ws-network
  my-redis:
    image: redis:7.4.0-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - ws-network
  frontend:
    build: ./frontend
    image: deno-frontend-image
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - WEBSOCKET_URL=ws://localhost:4000
    ports:
      - "8000:8000"

networks:
  ws-network:
    driver: overlay
    attachable: true